### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by robfe11** [danielgtaylor/atom-api-blueprint-preview#39]
Hi,

I just installed the plugin on the Atom 1.0.2, when trying to run it, I get the following error:

```
/bin/sh -c aglio -i /tmp/atom.apib -t /Users/rob/.atom/packages/api-blueprint-preview/templates/api-blueprint-preview.jade -o - { [Error: Cannot find module 'aglio-theme-/Users/rob/.atom/packages/api-blueprint-preview/templates/api-blueprint-preview.jade'] code: 'MODULE_NOT_FOUND' }
```

Any idea what the issue could be?

Thanks,

Rob

**Comment by nealeduncan** [comment]
I had this exact same issue on Windows.  Installing aglio@1.18.0 instead of 2.0 resolved this for me.

**Comment by sethlopezme** [comment]
I was getting the same error on OS X. As @nealeduncan suggested, I installed [aglio@1.18.0](https://github.com/danielgtaylor/aglio/tree/aglio-v1.x) and it works for me.

**Comment by danielgtaylor** [comment]
This looks like a regression in 2.0. I'll look into fixing it.

**Comment by stianborgesen** [comment]
Downgrading to aglio@1.18.0 did not work for me. Downgrading api-blueprint-preview however works for for now. 

$apm install api-blueprint-preview@0.5.0

**Comment by asux** [comment]
I have same issue. But it works with [aglio@v1.18.0](https://github.com/danielgtaylor/aglio/releases/tag/v1.18.0). Waiting for fix.

**Comment by danielgtaylor** [comment]
This should now be fixed. Please install Aglio 2.0.2.

**Comment by robfe11** [comment]
Awesome, thanks, it works!
